/**
 * Exercises performHttpsRequest() against a real local HTTPS server rather
 * than a mock, since the orchestration-level tests in webfetch.test.ts mock
 * this function away entirely. In particular, this proves that connecting
 * directly to a validated IP address while supplying `servername` for TLS
 * still completes a normal TLS handshake and certificate check against the
 * original hostname - the mechanism the whole SSRF design depends on.
 *
 * Uses a throwaway self-signed certificate generated by the system openssl
 * binary, valid only for the duration of this test file, on loopback only.
 * NODE_TLS_REJECT_UNAUTHORIZED is disabled only around the two requests that
 * need to trust that throwaway certificate, and is always restored
 * immediately afterward; production code never sets this itself.
 */
import {
  execFileSync,
} from "node:child_process";

import {
  createServer,
  type Server,
} from "node:https";

import {
  mkdtemp,
  readFile,
  rm,
} from "node:fs/promises";

import {
  tmpdir,
} from "node:os";

import {
  join,
} from "node:path";

import {
  afterAll,
  beforeAll,
  describe,
  expect,
  it,
} from "vitest";

import {
  performHttpsRequest,
} from "../src/webfetch.ts";

describe(
  "performHttpsRequest against a real local TLS server",
  () => {
    let server: Server;
    let port: number;
    let certDirectory: string;
    let originalTlsRejectUnauthorized: string | undefined;

    beforeAll(
      async () => {
        certDirectory =
          await mkdtemp(
            join(tmpdir(), "sky-code-webfetch-cert-"),
          );

        const keyPath =
          join(certDirectory, "key.pem");
        const certPath =
          join(certDirectory, "cert.pem");

        execFileSync(
          "openssl",
          [
            "req",
            "-x509",
            "-newkey",
            "rsa:2048",
            "-keyout",
            keyPath,
            "-out",
            certPath,
            "-days",
            "1",
            "-nodes",
            "-subj",
            "/CN=localhost",
          ],
          { stdio: "ignore" },
        );

        const [key, cert] =
          await Promise.all([
            readFile(keyPath),
            readFile(certPath),
          ]);

        server =
          createServer(
            { key, cert },
            (request, response) => {
              if (request.url === "/slow") {
                // Never respond, to exercise the request timeout path.
                return;
              }

              if (request.url === "/big") {
                response.writeHead(200, {
                  "content-type": "text/plain",
                });
                response.end(
                  "x".repeat(1000),
                );
                return;
              }

              response.writeHead(200, {
                "content-type": "text/plain",
                "x-received-host":
                  request.headers.host ?? "",
              });
              response.end("hello from the test server");
            },
          );

        await new Promise<void>(
          (resolve) => {
            server.listen(
              0,
              "127.0.0.1",
              () => resolve(),
            );
          },
        );

        const address =
          server.address();

        if (
          address === null ||
          typeof address === "string"
        ) {
          throw new Error(
            "Expected the test server to bind to a numeric port.",
          );
        }

        port = address.port;
        originalTlsRejectUnauthorized =
          process.env.NODE_TLS_REJECT_UNAUTHORIZED;
      },
    );

    afterAll(
      async () => {
        await new Promise<void>(
          (resolve) => server.close(() => resolve()),
        );

        await rm(
          certDirectory,
          { recursive: true, force: true },
        );
      },
    );

    it(
      "connects to a raw IP address while validating the certificate against servername",
      async () => {
        process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

        try {
          const result =
            await performHttpsRequest({
              address: "127.0.0.1",
              servername: "localhost",
              port,
              path: "/",
              headers: { Host: "localhost" },
              timeoutMs: 5000,
              maxBytes: 10_000,
            });

          expect(result.statusCode).toBe(200);
          expect(result.body.toString("utf8")).toBe(
            "hello from the test server",
          );
          expect(result.headers["x-received-host"]).toBe(
            "localhost",
          );
          expect(result.truncated).toBe(false);
        } finally {
          process.env.NODE_TLS_REJECT_UNAUTHORIZED =
            originalTlsRejectUnauthorized;
        }
      },
    );

    it(
      "truncates the body once maxBytes is exceeded",
      async () => {
        process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

        try {
          const result =
            await performHttpsRequest({
              address: "127.0.0.1",
              servername: "localhost",
              port,
              path: "/big",
              headers: { Host: "localhost" },
              timeoutMs: 5000,
              maxBytes: 100,
            });

          expect(result.truncated).toBe(true);
          expect(result.body.length).toBe(100);
        } finally {
          process.env.NODE_TLS_REJECT_UNAUTHORIZED =
            originalTlsRejectUnauthorized;
        }
      },
    );

    it(
      "rejects with a timeout error when the server never responds",
      async () => {
        process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

        try {
          await expect(
            performHttpsRequest({
              address: "127.0.0.1",
              servername: "localhost",
              port,
              path: "/slow",
              headers: { Host: "localhost" },
              timeoutMs: 200,
              maxBytes: 10_000,
            }),
          ).rejects.toMatchObject({
            name: "WebFetchNetworkError",
            kind: "timeout",
          });
        } finally {
          process.env.NODE_TLS_REJECT_UNAUTHORIZED =
            originalTlsRejectUnauthorized;
        }
      },
    );

    it(
      "rejects with a network error for a connection that is refused",
      async () => {
        await expect(
          performHttpsRequest({
            // Nothing listens on this port on loopback.
            address: "127.0.0.1",
            servername: "localhost",
            port: 1,
            path: "/",
            headers: { Host: "localhost" },
            timeoutMs: 5000,
            maxBytes: 10_000,
          }),
        ).rejects.toMatchObject({
          name: "WebFetchNetworkError",
          kind: "network",
        });
      },
    );
  },
);
