import type {
  ChatMessage,
} from "./chat.js";

import {
  HookRegistry,
  type HookMetadata,
} from "./hooks.js";

export const DEFAULT_RECENT_MESSAGE_COUNT =
  6;

export const APPROXIMATE_CHARACTERS_PER_TOKEN =
  4;

export type CompactionReason =
  | "manual"
  | "token-pressure";

export type ConversationSummarizer = (
  messages:
    readonly ChatMessage[],
) => Promise<string>;

export interface CompactConversationOptions {
  reason:
    CompactionReason;

  summarize:
    ConversationSummarizer;

  hookRegistry:
    HookRegistry;

  keepRecentMessages?:
    number;
}

export interface CompactionResult {
  compacted:
    boolean;

  reason:
    CompactionReason;

  beforeMessageCount:
    number;

  afterMessageCount:
    number;

  estimatedTokensBefore:
    number;

  droppedToolOutputCount:
    number;

  summary?:
    string;
}

function validateRecentMessageCount(
  value: number,
): number {
  if (
    !Number.isSafeInteger(
      value,
    ) ||
    value < 1
  ) {
    throw new Error(
      "keepRecentMessages must be a positive whole number",
    );
  }

  return value;
}

export function isStaleToolResultMessage(
  message:
    ChatMessage,
): boolean {
  return (
    message.role ===
      "user" &&
    message.content
      .trimStart()
      .startsWith(
        "Sky Code tool result for ",
      )
  );
}

export function estimateConversationTokens(
  messages:
    readonly ChatMessage[],
): number {
  const characterCount =
    messages.reduce(
      (
        total,
        message,
      ) =>
        total +
        message.content.length +
        message.role.length +
        4,
      0,
    );

  if (
    characterCount ===
      0
  ) {
    return 0;
  }

  return Math.ceil(
    characterCount /
      APPROXIMATE_CHARACTERS_PER_TOKEN,
  );
}

function removeStaleToolOutput(
  message:
    ChatMessage,
): ChatMessage {
  if (
    !isStaleToolResultMessage(
      message,
    )
  ) {
    return {
      role:
        message.role,
      content:
        message.content,
    };
  }

  const firstLine =
    message.content
      .split(
        /\r?\n/,
        1,
      )[0]
      ?.trim() ||
    "Sky Code tool result";

  return {
    role:
      message.role,
    content: [
      firstLine,
      "[Stale tool output omitted during context compaction.]",
    ].join(
      "\n",
    ),
  };
}

export function createCompactionSummaryMessage(
  summary: string,
): ChatMessage {
  const trimmedSummary =
    summary.trim();

  if (
    trimmedSummary ===
      ""
  ) {
    throw new Error(
      "Context compaction returned an empty summary",
    );
  }

  return {
    role:
      "user",
    content: [
      "Earlier conversation summary generated by Sky Code context compaction:",
      "",
      trimmedSummary,
    ].join(
      "\n",
    ),
  };
}

export async function compactConversation(
  messages:
    ChatMessage[],
  options:
    CompactConversationOptions,
): Promise<CompactionResult> {
  const keepRecentMessages =
    validateRecentMessageCount(
      options
        .keepRecentMessages ??
      DEFAULT_RECENT_MESSAGE_COUNT,
    );

  const beforeMessageCount =
    messages.length;

  const estimatedTokensBefore =
    estimateConversationTokens(
      messages,
    );

  const olderMessageCount =
    beforeMessageCount -
    keepRecentMessages;

  if (
    olderMessageCount <
      2
  ) {
    return {
      compacted:
        false,
      reason:
        options.reason,
      beforeMessageCount,
      afterMessageCount:
        beforeMessageCount,
      estimatedTokensBefore,
      droppedToolOutputCount:
        0,
    };
  }

  const originalMessages =
    messages.map(
      (
        message,
      ) => ({
        role:
          message.role,
        content:
          message.content,
      }),
    );

  const olderMessages =
    messages.slice(
      0,
      olderMessageCount,
    );

  const recentMessages =
    messages.slice(
      olderMessageCount,
    );

  const droppedToolOutputCount =
    olderMessages.filter(
      isStaleToolResultMessage,
    ).length;

  const messagesForSummary =
    olderMessages.map(
      removeStaleToolOutput,
    );

  const metadata:
    HookMetadata = {
    reason:
      options.reason,
    keepRecentMessages,
    droppedToolOutputCount,
  };

  await options
    .hookRegistry
    .run(
      "PreCompact",
      {
        messageCount:
          beforeMessageCount,
        reason:
          options.reason,
        estimatedTokens:
          estimatedTokensBefore,
        metadata,
      },
    );

  const summary =
    (
      await options
        .summarize(
          messagesForSummary,
        )
    ).trim();

  const summaryMessage =
    createCompactionSummaryMessage(
      summary,
    );

  const compactedMessages = [
    summaryMessage,
    ...recentMessages,
  ];

  messages.splice(
    0,
    messages.length,
    ...compactedMessages,
  );

  try {
    await options
      .hookRegistry
      .run(
        "PostCompact",
        {
          beforeMessageCount,
          afterMessageCount:
            messages.length,
          summary,
          metadata,
        },
      );
  } catch (error) {
    messages.splice(
      0,
      messages.length,
      ...originalMessages,
    );

    throw error;
  }

  return {
    compacted:
      true,
    reason:
      options.reason,
    beforeMessageCount,
    afterMessageCount:
      messages.length,
    estimatedTokensBefore,
    droppedToolOutputCount,
    summary,
  };
}
