import type {
  ChatMessage,
} from "./chat.js";

import type {
  CompactionStrategy,
} from "./config.js";

import {
  HookRegistry,
  type HookMetadata,
} from "./hooks.js";

export const DEFAULT_RECENT_MESSAGE_COUNT =
  20;

export const APPROXIMATE_CHARACTERS_PER_TOKEN =
  4;

export type CompactionReason =
  | "manual"
  | "token-pressure";

export type ConversationSummarizer = (
  messages:
    readonly ChatMessage[],
) => Promise<string>;

export interface CompactConversationOptions {
  reason:
    CompactionReason;

  strategy?:
    CompactionStrategy;

  summarize?:
    ConversationSummarizer;

  hookRegistry:
    HookRegistry;

  keepRecentMessages?:
    number;
}

export interface CompactionResult {
  compacted:
    boolean;

  reason:
    CompactionReason;

  strategy?:
    CompactionStrategy;

  beforeMessageCount:
    number;

  afterMessageCount:
    number;

  compactedTurnCount?:
    number;

  estimatedTokensBefore:
    number;

  estimatedTokensAfter?:
    number;

  estimatedTokenReduction?:
    number;

  droppedToolOutputCount:
    number;

  summary?:
    string;
}

function validateRecentMessageCount(
  value:
    number,
): number {
  if (
    !Number.isSafeInteger(
      value,
    ) ||
    value < 1
  ) {
    throw new Error(
      "keepRecentMessages must be a positive whole number",
    );
  }

  return value;
}

function validateStrategy(
  value:
    CompactionStrategy,
): CompactionStrategy {
  if (
    value !==
      "summarise" &&
    value !==
      "sliding-window"
  ) {
    throw new Error(
      'compactionStrategy must be either "summarise" or "sliding-window"',
    );
  }

  return value;
}

function cloneMessages(
  messages:
    readonly ChatMessage[],
): ChatMessage[] {
  return messages.map(
    (
      message,
    ) => ({
      role:
        message.role,

      content:
        message.content,
    }),
  );
}

export function isStaleToolResultMessage(
  message:
    ChatMessage,
): boolean {
  return (
    message.role ===
      "user" &&
    message.content
      .trimStart()
      .startsWith(
        "Sky Code tool result for ",
      )
  );
}

export function estimateConversationTokens(
  messages:
    readonly ChatMessage[],
): number {
  const characterCount =
    messages.reduce(
      (
        total,
        message,
      ) =>
        total +
        message.content.length +
        message.role.length +
        4,
      0,
    );

  if (
    characterCount ===
      0
  ) {
    return 0;
  }

  return Math.ceil(
    characterCount /
      APPROXIMATE_CHARACTERS_PER_TOKEN,
  );
}

function removeStaleToolOutput(
  message:
    ChatMessage,
): ChatMessage {
  if (
    !isStaleToolResultMessage(
      message,
    )
  ) {
    return {
      role:
        message.role,

      content:
        message.content,
    };
  }

  const firstLine =
    message.content
      .split(
        /\r?\n/,
        1,
      )[0]
      ?.trim() ||
    "Sky Code tool result";

  return {
    role:
      message.role,

    content: [
      firstLine,
      "[Stale tool output omitted during context compaction.]",
    ].join(
      "\n",
    ),
  };
}

export function createCompactionSummaryMessage(
  summary:
    string,
): ChatMessage {
  const trimmedSummary =
    summary.trim();

  if (
    trimmedSummary ===
      ""
  ) {
    throw new Error(
      "Context compaction returned an empty summary",
    );
  }

  return {
    role:
      "user",

    content: [
      "Earlier conversation summary generated by Sky Code context compaction:",
      "",
      trimmedSummary,
    ].join(
      "\n",
    ),
  };
}

export async function compactConversation(
  messages:
    ChatMessage[],

  options:
    CompactConversationOptions,
): Promise<CompactionResult> {
  const strategy =
    validateStrategy(
      options.strategy ??
        "summarise",
    );

  const keepRecentMessages =
    validateRecentMessageCount(
      options
        .keepRecentMessages ??
      DEFAULT_RECENT_MESSAGE_COUNT,
    );

  const beforeMessageCount =
    messages.length;

  const estimatedTokensBefore =
    estimateConversationTokens(
      messages,
    );

  const olderMessageCount =
    beforeMessageCount -
    keepRecentMessages;

  if (
    olderMessageCount <
      2
  ) {
    return {
      compacted:
        false,

      reason:
        options.reason,

      strategy,

      beforeMessageCount,

      afterMessageCount:
        beforeMessageCount,

      compactedTurnCount:
        0,

      estimatedTokensBefore,

      estimatedTokensAfter:
        estimatedTokensBefore,

      estimatedTokenReduction:
        0,

      droppedToolOutputCount:
        0,
    };
  }

  const originalMessages =
    cloneMessages(
      messages,
    );

  const olderMessages =
    messages.slice(
      0,
      olderMessageCount,
    );

  const recentMessages =
    cloneMessages(
      messages.slice(
        olderMessageCount,
      ),
    );

  const droppedToolOutputCount =
    olderMessages.filter(
      isStaleToolResultMessage,
    ).length;

  const metadata:
    HookMetadata = {
    reason:
      options.reason,

    strategy,

    keepRecentMessages,

    droppedToolOutputCount,
  };

  await options
    .hookRegistry
    .run(
      "PreCompact",
      {
        messageCount:
          beforeMessageCount,

        reason:
          options.reason,

        estimatedTokens:
          estimatedTokensBefore,

        metadata,
      },
    );

  let summary:
    string | undefined;

  let compactedMessages:
    ChatMessage[];

  if (
    strategy ===
      "summarise"
  ) {
    if (
      options.summarize ===
        undefined
    ) {
      throw new Error(
        "Summarise compaction requires a summarizer",
      );
    }

    const messagesForSummary =
      olderMessages.map(
        removeStaleToolOutput,
      );

    summary =
      (
        await options
          .summarize(
            messagesForSummary,
          )
      ).trim();

    compactedMessages = [
      createCompactionSummaryMessage(
        summary,
      ),
      ...recentMessages,
    ];
  } else {
    compactedMessages =
      recentMessages;
  }

  messages.splice(
    0,
    messages.length,
    ...compactedMessages,
  );

  const estimatedTokensAfter =
    estimateConversationTokens(
      messages,
    );

  const estimatedTokenReduction =
    Math.max(
      0,
      estimatedTokensBefore -
        estimatedTokensAfter,
    );

  const compactedTurnCount =
    beforeMessageCount -
    messages.length;

  metadata.compactedTurnCount =
    compactedTurnCount;

  metadata.estimatedTokensAfter =
    estimatedTokensAfter;

  metadata.estimatedTokenReduction =
    estimatedTokenReduction;

  try {
    await options
      .hookRegistry
      .run(
        "PostCompact",
        {
          beforeMessageCount,

          afterMessageCount:
            messages.length,

          summary,

          metadata,
        },
      );
  } catch (error) {
    messages.splice(
      0,
      messages.length,
      ...originalMessages,
    );

    throw error;
  }

  return {
    compacted:
      true,

    reason:
      options.reason,

    strategy,

    beforeMessageCount,

    afterMessageCount:
      messages.length,

    compactedTurnCount,

    estimatedTokensBefore,

    estimatedTokensAfter,

    estimatedTokenReduction,

    droppedToolOutputCount,

    summary,
  };
}
